language: python
python:
  - "3.7"
before_install:
  - python --version
  - pip install -U pip
install:
  - pip install -Ur requirements.txt
  - pip install -e .
script:
  - pytest --cov=kotidostories