version: '3'

services:
    postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data/  
      ports:
        - 127.0.0.1:5432:5432
      environment:
        POSTGRES_USER: dev
        POSTGRES_PASSWORD: dev123
        POSTGRES_DB: dev_db

volumes:
    postgres_data: